### ISSUE TITLE
Feature: Support Musicbrainz Collaborations

### ISSUE THREAD

**Issue by drewcovi** [pkscout/script.artistslideshow#39]
Since 2011 Musicbrainz is depreciating the notion of collaborations as independent artist entries as per the following criteria in the [Next Generation Schema](https://musicbrainz.org/doc/Next_Generation_Schema):

Collaboration Rules: http://musicbrainz.org/relationship/75c09861-6857-4ec0-9729-84eefde7fc86

> This relationship should only be used when artist credits can't be easily used. Normally this implies the collaboration receives a new name: if X and Y collaborate as "X & Y" a new artist should not be created, as we can simply credit it as "X" & "Y" through artist credits."

This can become confusing since breaking **Tom Petty & The Heartbreakers** into **Tom Petty** & **The Heartbreakers** will result in potentially many results for **The Heartbreakers**.  

Disambiguation however can be accomplished using **aliases** (so this one example of The Heartbreakers would use "Tom Petty & The Heartbreakers" as an alias to avoid confusion)

Using aliases is also backwards compatible: Artists without any assigned aliases will still return as a result when searching using the alias api query.

**Comment by drewcovi** [comment]
Just a sidenote: really love this addon, so thanks so much for taking the time with this.

We had a new years party, and I was using the Sonos controller addon which taps into this for a slideshow of any given artist, but almost always failed on collaborations.

The lack of results was something I was very excited to fix, so please take this as a squeaky wheel from a very happy contributor.

**Comment by pkscout** [comment]
I'm closing this because as of 2.0 AS requires that the MusicBrainz ID be provided by Kodi, so it has to be scraped into the music library.  AS no longer has any logic for finding MBIDs.
