### ISSUE TITLE
Feature: Maximum alpha value for slide pictures

### ISSUE THREAD

**Issue by OtakuWally** [pkscout/script.artistslideshow#40]
First I would like to thank you for this GREAT plugin! For someone who is listening to a LOT of music your addon is a definitve must-have.

I really like the way the addon handles all the additional artist info and brings it to the screen. However I have noticed that when the single slideshow pictures are being changed (during the transitions), your can see the visualizer, but when the transition has ended, the visualizer is invisible. I think it would be a great idea to be able to set a maximum alpha value for the slideshow pictures, so that the visualizer would be visible ALL THE TIME, if this is possible.

Once again: THANKS for your GREAT WORK!

**Comment by pkscout** [comment]
I'll look into it, but I'm pretty sure that's something that would have to be handled by the Kodi skin you're using.  AS technically doesn't display anything, it just downloads images and then tells the skin where they are.  The skin decides what to do with them.
