### ISSUE TITLE
wiki info outdated?

### ISSUE THREAD

**Issue by riebling** [pkscout/script.artistslideshow#45]
Somem of the [wiki info](http://kodi.wiki/view/Add-on:Artist_Slideshow) linked from here seems quite out of date. Is there a better location of the most up to date / better / most accurate help for setting up AS?

For example
```
Go to the Kodi installation root folder (see this wiki page under special://xbmc for the path for your operating system). Then go to addons --> skin.confluence. Quit Kodi, modify the appropriate files, and then start up Kodi again. 
```
a. For Kodi Jarvis, the path seems to be special:/profile/addon_data/skin.confluence in File Manager, or /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/skin.confluence/ (for Android) not what's above or on the wiki.  
b. at the point a person is reading the wiki, 'the appropriate files' have yet to be mentioned or named or defined yet (?) - it takes a leap of faith to keep reading and trust that they are about to be explained. :)  
c. later, when the appropriate file(s) ARE named, a file named MusicVisualization.xml does not seem to even exist in the skin.confluence folder

I understand it's a pain to update documentation and track changes introduced in new Kodi versions, but it's also a pain to find or be led to documentation that is just plain wrong. I guess in the spirit of open source this is the place where I volunteer to fix it. Meanwhile I'll try your modified Confluence skin for my Kodi version and then maybe have some success - thanks for putting so much work into this, and being so responsive on the forum!

**Comment by pkscout** [comment]
Yea, I wish the Kodi folks would provide a wiki page with the skin location information, but they don't.  I do need to update this for some of the new stuff that just got released, so I'll look at updating it.  Honestly at this point I think I'll probably put a note in saying that if you don't know where the skin files are, then you shouldn't update them.  Between my mod and other skins, there are plenty of options to use AS now that you shouldn't need to modify skin files unless you really, really want to.

**Comment by riebling** [comment]
Thanks and just to acknowledge 'success' I installed your Confluence mod and got things working - finally can enjoy Artist Slideshow!
