### ISSUE TITLE
BAD last.fm similar artist images 

### ISSUE THREAD

**Issue by mjnman** [pkscout/script.artistslideshow#53]
The Similar Artists images feature don't work because last.fm search found empty images in XML output (only star images).
Below an example output of bad images inside XML file:

http://ws.audioscrobbler.com/2.0/?autocorrect=1&api_key=afe7e856e4f4089fc90f841980ea1ada&limit=50&method=artist.getSimilar&artist=Anna+Nalick

example the first one url is https://lastfm.freetls.fastly.net/i/u/34s/2a96cbd8b46e442fc41c2b86b821562f.png and it's a star image and so on with others urls ...

**Comment by pkscout** [comment]
Last.fm dropped support for image retrieval via the API some time ago.  I had removed that functionality altogether, but there was feedback that folks preferred the stars to nothing, so I reverted back.  Unfortunately over the years Last.fm has made their API less and less useful and didn't listen to the feedback lots of programmer gave them, so we're stuck with whatever crumbs they decide to give us.
