### ISSUE TITLE
Matrix version

### ISSUE THREAD

**Issue by Bilbo** [pkscout/script.artistslideshow#57]
After updating to Matrix version the slideshow doesn't work anymore. Tried installing latest commit and getting xbmc.python dependency 2.26 error now.

**Comment by pkscout** [comment]
If you installed Artist Slideshow from a zip from this Github repo, then when you updated to Matrix it didn't auto update.  My suggestion would be to delete `userdata/addons/script.artistslideshow` folder and then install AS from the main Kodi repo. That will install the correct version for Matrix, and none of your settings should be lost.

**Comment by Bilbo** [comment]
Thanks pkscout.
That worked great.
Love the script and glad it's built into Kodi repo.
Great work!
