### ISSUE TITLE
How to display the original size of a picture

### ISSUE THREAD

**Issue by harvey58** [pkscout/script.artistslideshow#58]
Vertical version of the picture can not be fully displayed, has been enlarged, how to display the original size of the picture

**Comment by pkscout** [comment]
Artist Slideshow does not actually display the image, it only tells the skin you are using what image to display. The actual display is up to the skin.  If you are using the default Estuary skin, there is no option to change the behavior you describe. You can use my Estuary mod, which does have a skin setting to keep the original aspect ratio of images.

Leia mod: https://forum.kodi.tv/showthread.php?tid=333143
Matrix mod: https://forum.kodi.tv/showthread.php?tid=356349

If you are using any other skin, you need to contact the skin author.
